const express = require("express")
const bodyParser = require("body-parser")
const cookieParser = require("cookie-parser")
const path = require("path")
const ejs = require("ejs")

const app = express()
app.use(bodyParser.json())
app.use(cookieParser())
app.set("view-engine", "ejs")
app.use('/', express.static(path.join(__dirname, '/')))
app.listen(3003)
